#!/bin/bash
# check ping
inetCheck() {
clear
echo "Checking Internet..."

host="google.com"

pa=$(fping -t1500 $host | awk '{print $3}')
echo "Ping $host attempt #1" $pa
pb=$(fping -t1500 $host | awk '{print $3}')
echo "Ping $host attempt #2" $pb
pc=$(fping -t1500 $host | awk '{print $3}')
echo "Ping $host attempt #3" $pc

if [ "$pa" != "alive" ] && [ "$pb" != "alive" ] && [ "$pc" != "alive" ]; then
	echo "Internet Down!"
	inetCheck
else
	echo "Internet Up!"
    	echo "Updating NTP..."
	ntpdate -s time.cloudflare.com
	clear
fi
}
inetCheck
