#!/bin/bash
#!/bin/bash
# injek monitor Libernet by Laksamadi Guko

restartinjek (){
killall -q serviceinjekmon
screen -AmdS serviceinjekmon /usr/bin/serviceinjekmon
}


if [ "$1" != "" ]; then
echo "$1" > /root/injekmon.txt
cat /root/injekmon.txt
restartinjek
else
restartinjek
fi
