#!/bin/bash

wget --show-progress --progress=bar:force -qO /usr/bin/injekmon https://raw.githubusercontent.com/laksa19/openwrt-tools/master/injekmon/injekmon && chmod +x /usr/bin/injekmon
wget --show-progress --progress=bar:force -qO /usr/bin/serviceinjekmon https://raw.githubusercontent.com/laksa19/openwrt-tools/master/injekmon/serviceinjekmon && chmod +x /usr/bin/serviceinjekmon
